version: '3.7'

networks:
  app-net:

services:
  app:
    image: satori_app
    build:
      context: .
      target: builder
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"

  migration:
    environment:
      - DATABASE_URL
    image: satori_app:latest
    security_opt:
      - seccomp:unconfined
    entrypoint: /bin/sh -c "dbmate wait && dbmate up"
    depends_on:
      - db
    networks:
      - app-net
